import { createWriteStream } from 'node:fs';
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import type { DeployPlan } from '../deploy.js';
import type { MatchRow, TournamentRow } from './store.js';

/**
 * The CS2 match server recipe.
 *
 * One shared installation (the game is ~35 GB; one copy, not one per match)
 * holds the game plus the competitive stack: Metamod, CounterStrikeSharp and
 * MatchZy. The joedwards32/cs2 image does the heavy lifting -- steamcmd
 * install and update on boot, then it sources pre.sh before starting the
 * server. That hook is ours: it unpacks the addon bundle this module
 * downloads and re-patches gameinfo.gi, both idempotently, so a game update
 * that overwrites the patch heals on the next boot.
 *
 * Match servers share the installation but nothing else: each gets its own
 * port, GSLT, passwords and event token, all per match and all retired with
 * it. Boots are serialized by the orchestrator so two steamcmd runs never
 * write the shared directory at once.
 */

export const CS2_IMAGE = 'joedwards32/cs2:latest';

/** Directory name under the appdata root that holds the shared install. */
export const CS2_SHARED_DIR = 'cs2-match';

/** Where the image mounts the installation. */
const STEAMAPPDIR = '/home/steam/cs2-dedicated';

/**
 * Host ports for match servers, one per concurrent match. Deliberately away
 * from 27015: a standing CS2 server someone deploys normally keeps its
 * conventional port, and match servers never fight it for the number.
 */
export const MATCH_PORT_RANGE = { first: 27051, last: 27058 };

const METAMOD_LATEST = 'https://mms.alliedmods.net/mmsdrop/2.0/mmsource-latest-linux';
const MATCHZY_RELEASES = 'https://api.github.com/repos/shobhit-pathak/MatchZy/releases/latest';

export class Cs2SetupError extends Error {}

async function download(url: string, to: string): Promise<void> {
  const response = await fetch(url, { signal: AbortSignal.timeout(300_000) });
  if (!response.ok || !response.body) {
    throw new Cs2SetupError(`Download failed (${response.status}): ${url}`);
  }
  await pipeline(Readable.fromWeb(response.body as never), createWriteStream(to));
  // The CS2 container's own user has to be able to read what we fetched.
  await chmod(to, 0o644);
}

/**
 * The pre-start hook the image sources after steamcmd and before the game.
 * It runs as the container's own user inside the shared volume, which makes
 * it the one place addon files can be unpacked with the right owner without
 * anyone doing chown gymnastics.
 */
function buildPreScript(stamp: string): string {
  return `#!/bin/bash
# Generated by GameKeepr -- prepares the competitive stack before each start.
# Sourced by the image's entry.sh after steamcmd has updated the game.
GK="\${STEAMAPPDIR}/gamekeepr"
CSGO="\${STEAMAPPDIR}/game/csgo"
STAMP="${stamp}"

if [ -d "$CSGO" ] && [ -d "$GK" ]; then
    if [ ! -f "$GK/.installed-$STAMP" ]; then
        echo "GameKeepr: installing Metamod + CounterStrikeSharp + MatchZy ($STAMP)"
        [ -f "$GK/metamod.tar.gz" ] && tar xzf "$GK/metamod.tar.gz" -C "$CSGO"
        [ -f "$GK/matchzy.zip" ] && unzip -o -q "$GK/matchzy.zip" -d "$CSGO"
        touch "$GK/.installed-$STAMP"
    fi
    # A validated update rewrites gameinfo.gi; re-adding the search path is
    # cheap and idempotent, so it simply happens on every boot.
    GI="$CSGO/gameinfo.gi"
    if [ -f "$GI" ] && ! grep -q 'csgo/addons/metamod' "$GI"; then
        sed -i '/Game_LowViolence/a \\\t\\\t\\\tGame\\\tcsgo/addons/metamod' "$GI"
        echo "GameKeepr: patched gameinfo.gi for Metamod"
    fi
fi
`;
}

/**
 * Downloads the addon bundle into the shared directory and writes pre.sh.
 *
 * Runs before a provision and is cheap when already done: the versions file
 * records what was fetched, and matching versions mean no network at all.
 * Fetching re-resolves "latest" each time it does run, so a MatchZy release
 * arrives by itself the next time a tournament spins up.
 */
export async function ensureCs2Addons(
  sharedDir: string,
  log: (message: string) => void,
): Promise<void> {
  const bundleDir = join(sharedDir, 'gamekeepr');
  await mkdir(bundleDir, { recursive: true });
  // The image's steam user (uid 1000) must create the install here, and the
  // portal's own uid is not that, so the shared root is deliberately open.
  await chmod(sharedDir, 0o777).catch(() => undefined);
  await chmod(bundleDir, 0o777).catch(() => undefined);

  const versionsPath = join(bundleDir, 'versions.json');
  let current: { metamod?: string; matchzy?: string } = {};
  try {
    current = JSON.parse(await readFile(versionsPath, 'utf8')) as typeof current;
  } catch {
    // First run, or someone deleted it: fetch fresh.
  }

  const metamodName = (
    await (await fetch(METAMOD_LATEST, { signal: AbortSignal.timeout(20_000) })).text()
  ).trim();
  if (!/^mmsource-[\w.-]+\.tar\.gz$/.test(metamodName)) {
    throw new Cs2SetupError(`Metamod latest answered something unexpected: "${metamodName}"`);
  }

  const releaseResponse = await fetch(MATCHZY_RELEASES, {
    headers: { accept: 'application/vnd.github+json' },
    signal: AbortSignal.timeout(20_000),
  });
  if (!releaseResponse.ok) {
    throw new Cs2SetupError(`GitHub answered ${releaseResponse.status} for the MatchZy release.`);
  }
  const release = (await releaseResponse.json()) as {
    tag_name?: string;
    assets?: Array<{ name: string; browser_download_url: string }>;
  };
  const asset = (release.assets ?? []).find((a) => a.name.includes('with-cssharp-linux'));
  if (!asset) {
    throw new Cs2SetupError(
      `The MatchZy release ${release.tag_name ?? '?'} has no with-cssharp-linux bundle.`,
    );
  }

  if (current.metamod !== metamodName) {
    log(`Downloading Metamod ${metamodName}`);
    await download(`https://mms.alliedmods.net/mmsdrop/2.0/${metamodName}`, join(bundleDir, 'metamod.tar.gz'));
  }
  if (current.matchzy !== asset.name) {
    log(`Downloading MatchZy ${asset.name}`);
    await download(asset.browser_download_url, join(bundleDir, 'matchzy.zip'));
  }

  const stamp = `${metamodName}-${asset.name}`.replace(/[^A-Za-z0-9.-]+/g, '_');
  await writeFile(join(sharedDir, 'pre.sh'), buildPreScript(stamp), { mode: 0o755 });
  await writeFile(versionsPath, JSON.stringify({ metamod: metamodName, matchzy: asset.name }), {
    mode: 0o644,
  });
}

export interface MatchServerInput {
  /** Container name; also what rcon and the teardown address. */
  containerName: string;
  serverName: string;
  port: number;
  password: string;
  rconPassword: string;
  /** Minted per match; absent means LAN-only (no GSLT configured). */
  gslt: string | null;
  maxPlayers: number;
  network: string;
  /** The shared install, in both of the portal's two views of the host. */
  sharedPath: string;
  sharedHostPath: string;
}

/** The same DeployPlan shape every portal-made container goes through. */
export function buildMatchServerPlan(input: MatchServerInput): DeployPlan {
  const portKeyTcp = `${input.port}/tcp`;
  const portKeyUdp = `${input.port}/udp`;
  return {
    containerName: input.containerName,
    serverId: input.containerName,
    image: CS2_IMAGE,
    appdataPath: input.sharedPath,
    appdataHostPath: input.sharedHostPath,
    createPaths: [input.sharedPath],
    network: input.network,
    env: [
      `CS2_SERVERNAME=${input.serverName.replace(/[\r\n]/g, ' ')}`,
      `CS2_PORT=${input.port}`,
      `CS2_PW=${input.password}`,
      `CS2_RCONPW=${input.rconPassword}`,
      `CS2_MAXPLAYERS=${input.maxPlayers}`,
      // Competitive defaults; MatchZy takes over the rules once live.
      'CS2_GAMEALIAS=competitive',
      'CS2_LAN=0',
      'STEAMAPPVALIDATE=0',
      ...(input.gslt ? [`SRCDS_TOKEN=${input.gslt}`] : []),
    ],
    binds: [`${input.sharedHostPath}:${STEAMAPPDIR}`],
    portBindings: {
      [portKeyTcp]: [{ HostPort: String(input.port) }],
      [portKeyUdp]: [{ HostPort: String(input.port) }],
    },
    exposed: { [portKeyTcp]: {}, [portKeyUdp]: {} },
    addedPorts: [],
  };
}

/**
 * The match config MatchZy fetches from the portal.
 *
 * Shaped per MatchZy's remote match documentation: a maplist longer than
 * num_maps starts the in-game veto (the Q16 decision), an exact-length list
 * plays in order. Players are Steam64 ids; whoever is not on either list
 * cannot take a player slot on this server.
 */
export function buildMatchZyConfig(args: {
  match: MatchRow;
  tournament: TournamentRow;
  teamAName: string;
  teamBName: string;
  teamAPlayers: Record<string, string>;
  teamBPlayers: Record<string, string>;
}): Record<string, unknown> {
  const { match, tournament } = args;
  return {
    // MatchZy wants an integer; events are matched by token, so any stable
    // number will do and seconds-of-creation reads well in server logs.
    matchid: Math.floor((match.scheduledAt ?? Date.now()) / 1000),
    team1: { name: args.teamAName, players: args.teamAPlayers },
    team2: { name: args.teamBName, players: args.teamBPlayers },
    num_maps: match.bestOf,
    maplist: tournament.mapPool,
    skip_veto: tournament.mapPool.length <= match.bestOf,
    side_type: 'standard',
    clinch_series: true,
    players_per_team: tournament.teamSize,
    min_players_to_ready: tournament.teamSize,
    cvars: {
      hostname: `GameKeepr — ${tournament.name}`,
    },
  };
}
