/**
 * Composing a game server container ourselves, instead of taking a template.
 *
 * The Unraid catalogue path trusts whoever wrote the template. This path
 * trusts two parties only: Valve's official steamcmd image, and Steam's own
 * depots for the chosen app id. Everything between them -- how the download
 * happens, which user the game runs as, how it starts -- is a shell script
 * this module writes, which lands inside the server's own volume where the
 * Files tab can show it and an operator can read exactly what will run.
 *
 * The layout deliberately mirrors the ich777 fleet convention
 * (/serverdata/steamcmd + /serverdata/serverfiles), so every other part of
 * the portal -- backups, mods, save discovery, the settings specs for
 * VALIDATE and GAME_PARAMS -- works on these servers unchanged.
 */

import { chown, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { DeployPlan } from '../deploy.js';
import { slugify } from '../deploy.js';
import { identifyGame, type GameProfile } from '../games.js';

export const STEAM_IMAGE = 'steamcmd/steamcmd:latest';
const SCRIPT_PATH = '/serverdata/steamcmd/gamekeep-start.sh';

export interface SteamComposeRequest {
  appId: number;
  appName: string;
  /** The display name the operator chose; slugified for ids and paths. */
  name: string;
  /** The launch line, relative to the install directory. One line of shell. */
  command: string;
  ports: Array<{ container: number; host: number; protocol: 'tcp' | 'udp' }>;
  gameParams: string;
  validate: boolean;
  steamUsername?: string;
  steamPassword?: string;
}

export function buildStartScript(req: { appId: number; appName: string; command: string }): string {
  return `#!/bin/bash
# Generated by GameKeepr -- ${req.appName} (Steam app ${req.appId}).
#
# This script IS the container: it downloads the server through SteamCMD and
# then becomes it. It lives in the steamcmd volume, so it survives restarts,
# is visible in the Files tab, and can be edited there if the game needs
# something unusual. The container runs it on every start, which is also how
# the server picks up its own updates.
set -uo pipefail

APP_ID="${req.appId}"
STEAMCMD_DIR="/serverdata/steamcmd"
SERVER_DIR="/serverdata/serverfiles"
PUID="\${PUID:-99}"
PGID="\${PGID:-100}"

mkdir -p "$STEAMCMD_DIR" "$SERVER_DIR"

# The game runs as an ordinary user, never as root. Its home is the steamcmd
# volume, so Steam's own state survives the container being recreated.
if ! getent group "$PGID" >/dev/null 2>&1; then
    groupadd -g "$PGID" gamekeep
fi
if ! getent passwd "$PUID" >/dev/null 2>&1; then
    useradd -u "$PUID" -g "$PGID" -d "$STEAMCMD_DIR" -s /bin/bash gamekeep
fi
RUN_AS="$(getent passwd "$PUID" | cut -d: -f1)"
export HOME="$STEAMCMD_DIR"

# Full ownership pass only on first run; a recursive chown over a large
# install on every start helps nobody.
if [ ! -f "$STEAMCMD_DIR/.gamekeep-owned" ]; then
    chown -R "$PUID:$PGID" /serverdata
    touch "$STEAMCMD_DIR/.gamekeep-owned"
else
    chown "$PUID:$PGID" /serverdata "$STEAMCMD_DIR" "$SERVER_DIR"
fi

echo "---GameKeepr: updating app $APP_ID through SteamCMD---"
if [ -n "\${USERNAME:-}" ]; then
    LOGIN=(+login "$USERNAME" "\${PASSWRD:-}")
else
    LOGIN=(+login anonymous)
fi
if [ "\${VALIDATE:-false}" = "true" ]; then
    UPDATE=(+app_update "$APP_ID" validate)
else
    UPDATE=(+app_update "$APP_ID")
fi
# force_install_dir must come before login, per Valve's own documentation.
runuser -u "$RUN_AS" -- /usr/bin/steamcmd \\
    +force_install_dir "$SERVER_DIR" \\
    "\${LOGIN[@]}" \\
    "\${UPDATE[@]}" \\
    +quit
STATUS=$?
if [ $STATUS -ne 0 ]; then
    echo "---GameKeepr: SteamCMD exited with $STATUS; refusing to start a half-installed server---"
    echo "---If this mentions a subscription or licence, this app does not allow anonymous downloads:"
    echo "---set USERNAME and PASSWRD on the container to a Steam account that owns it."
    exit $STATUS
fi

# Many servers dlopen steamclient.so from ~/.steam/sdk{32,64}; without it they
# start and then quietly abort. SteamCMD ships both, so they are linked here.
mkdir -p "$HOME/.steam"
for arch in 32 64; do
    lib="$(find "$HOME" -name steamclient.so -path "*linux$arch*" 2>/dev/null | head -1)"
    if [ -n "$lib" ]; then
        mkdir -p "$HOME/.steam/sdk$arch"
        ln -sf "$lib" "$HOME/.steam/sdk$arch/steamclient.so"
    fi
done
chown -R "$PUID:$PGID" "$HOME/.steam" 2>/dev/null || true

echo "---GameKeepr: starting the server---"
cd "$SERVER_DIR"
${startBlock(req.command)}`;
}

/**
 * The last lines of the start script: run the given command, or -- when none
 * was given because Steam's app info had no Linux launch entry -- find the
 * server's own start script by convention. The names are tried in order of
 * how strongly they announce themselves; the first hit wins, and no hit means
 * a loud refusal with the directory's scripts listed, never a guess between
 * two.
 */
function startBlock(command: string): string {
  if (command.trim()) {
    /*
     * The command is stored single-quoted, with embedded quotes escaped the
     * POSIX way, so the script's own (root) shell never parses a character of
     * it as code — interpolating it into a double-quoted bash -c string let a
     * $(...) in the command run as root before runuser ever happened. The
     * value is expanded into the inner command line below, where the
     * UNPRIVILEGED shell parses it: substitutions and quoting in the
     * operator's command still work, they just work as the right user.
     */
    const singleQuoted = command.replace(/'/g, `'\\''`);
    return `# The launch line came from Steam's own app info and was shown at
# deploy time. Held in a variable so no shell above runuser interprets it.
GK_COMMAND='${singleQuoted}'
# Some depots ship their binaries without the executable bit.
FIRST_WORD=$(printf '%s' "$GK_COMMAND" | awk '{print $1}')
if [ -n "$FIRST_WORD" ] && [ -f "$FIRST_WORD" ]; then chmod +x "$FIRST_WORD" 2>/dev/null || true; fi
# GAME_PARAMS is appended so arguments can be tuned from the Settings tab
# without editing this script.
exec runuser -u "$RUN_AS" -- bash -c "cd '$SERVER_DIR'; exec $GK_COMMAND \${GAME_PARAMS:-}"
`;
  }
  return `# No start command was given: Steam's app info had no Linux launch entry.
# Dedicated servers almost always ship their own start script under a
# conventional name; the first of these that exists is the server.
CANDIDATE=""
for name in startserver.sh StartServer.sh start-server.sh start_server.sh runserver.sh run_server.sh launch.sh start.sh run.sh; do
    if [ -f "$SERVER_DIR/$name" ]; then
        CANDIDATE="$name"
        break
    fi
done
if [ -z "$CANDIDATE" ]; then
    echo "---GameKeepr: no start command was set and no conventional start script was found.---"
    echo "---Shell scripts in the install directory:---"
    ls "$SERVER_DIR"/*.sh 2>/dev/null || echo "(none)"
    echo "---Set the start line in this file (Files tab: steamcmd/gamekeep-start.sh) and restart.---"
    exit 78
fi
echo "---GameKeepr: no start command was set; found $CANDIDATE and starting it.---"
echo "---(Edit steamcmd/gamekeep-start.sh in the Files tab to change this.)---"
chmod +x "$SERVER_DIR/$CANDIDATE" 2>/dev/null || true
exec runuser -u "$RUN_AS" -- bash -c "cd '$SERVER_DIR'; exec './$CANDIDATE' \${GAME_PARAMS:-}"
`;
}

/**
 * The same server as a compose file.
 *
 * The container is created through the Docker API, but this file is written
 * beside the start script as the honest, portable record of what was made:
 * anyone can take it to another machine and get the same server without the
 * portal. It is documentation that happens to be executable.
 */
export function buildComposeFile(req: SteamComposeRequest, hostRoot: string): string {
  const slug = slugify(req.name);
  const ports = req.ports
    .map((p) => `      - "${p.host}:${p.container}/${p.protocol}"`)
    .join('\n');
  return `# Generated by GameKeepr -- ${req.appName} (Steam app ${req.appId}).
# The portal created this container through the Docker API; this file is the
# same server in compose form, so it can be reproduced anywhere without the
# portal. The start behaviour lives in steamcmd/gamekeep-start.sh.
services:
  ${slug}:
    image: ${STEAM_IMAGE}
    container_name: ${req.name}
    restart: unless-stopped
    entrypoint: ["bash", "${SCRIPT_PATH}"]
    stdin_open: true
    environment:
      GAME_ID: "${req.appId}"
      GAME_PARAMS: "${req.gameParams.replace(/"/g, '\\"')}"
      VALIDATE: "${req.validate}"
      PUID: "99"
      PGID: "100"${req.steamUsername ? `\n      USERNAME: "${req.steamUsername}"\n      PASSWRD: "***"` : ''}
${ports ? `    ports:\n${ports}` : '    # no published ports'}
    volumes:
      - ${join(hostRoot, slug, 'steamcmd').replace(/\\/g, '/')}:/serverdata/steamcmd
      - ${join(hostRoot, slug, 'serverfiles').replace(/\\/g, '/')}:/serverdata/serverfiles
`;
}

/**
 * Writes the start script and the compose twin into the server's volume —
 * BEFORE the container exists, so the very first start already runs the
 * reviewed script. One writer for the Steam deploy route and the validation
 * runner; the chown mirrors Unraid's appdata convention and is best-effort.
 */
export async function writeSteamScaffold(
  plan: { appdataPath: string },
  req: SteamComposeRequest,
  hostRoot: string,
): Promise<void> {
  const scriptDir = join(plan.appdataPath, 'steamcmd');
  await mkdir(scriptDir, { recursive: true });
  await writeFile(join(scriptDir, 'gamekeep-start.sh'), buildStartScript(req), { mode: 0o755 });
  await writeFile(join(scriptDir, 'docker-compose.yml'), buildComposeFile(req, hostRoot));
  await chown(scriptDir, 99, 100).catch(() => undefined);
}

export function buildSteamPlan(
  req: SteamComposeRequest,
  appdataRoot: string,
  appdataHostRoot: string,
  gameNetwork: string,
): { plan: DeployPlan; game: GameProfile | null } {
  const serverId = slugify(req.name);
  const appdataPath = join(appdataRoot, serverId);
  const appdataHostPath = join(appdataHostRoot, serverId);

  const exposed: DeployPlan['exposed'] = {};
  const portBindings: DeployPlan['portBindings'] = {};
  for (const port of req.ports) {
    const key = `${port.container}/${port.protocol}`;
    exposed[key] = {};
    portBindings[key] = [{ HostPort: String(port.host) }];
  }

  /*
   * The registry's opinion still applies here: a required port the operator's
   * list missed is added, exactly as on the template path -- this game not
   * being installed from a template does not change what it needs.
   */
  const game = identifyGame(req.appName, '');
  const addedPorts: string[] = [];
  for (const needed of game?.ports ?? []) {
    if (!needed.required) continue;
    const key = `${needed.port}/${needed.protocol}`;
    if (portBindings[key]) continue;
    exposed[key] = {};
    portBindings[key] = [{ HostPort: String(needed.port) }];
    addedPorts.push(`${key} (${needed.purpose})`);
  }

  const env = [
    `GAME_ID=${req.appId}`,
    `GAME_PARAMS=${req.gameParams.replace(/[\r\n]/g, ' ')}`,
    `VALIDATE=${req.validate}`,
    'PUID=99',
    'PGID=100',
  ];
  if (req.steamUsername) {
    env.push(`USERNAME=${req.steamUsername}`, `PASSWRD=${req.steamPassword ?? ''}`);
  }

  return {
    game,
    plan: {
      containerName: req.name,
      serverId,
      image: STEAM_IMAGE,
      appdataPath,
      appdataHostPath,
      createPaths: [join(appdataPath, 'steamcmd'), join(appdataPath, 'serverfiles')],
      network: gameNetwork,
      env,
      binds: [
        `${join(appdataHostPath, 'steamcmd')}:/serverdata/steamcmd`,
        `${join(appdataHostPath, 'serverfiles')}:/serverdata/serverfiles`,
      ],
      portBindings,
      exposed,
      addedPorts,
      entrypoint: ['bash', SCRIPT_PATH],
      // So the Console tab can type at games that read stdin.
      openStdin: true,
    },
  };
}
